[package]
name = "rustyhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.13"
dotenv = "0.15.0"
env_logger = "0.10.1"
git2 = "0.18.1"
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
log = "0.4.20"
rusoto_core = "0.48.0"
rusoto_sqs = "0.48.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shiplift = "0.7.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.30"
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
cron = "0.12.0"
chrono = "0.4.32"
datetime = "0.5.2"
