[package]
name = "rustyhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.13"
env_logger = "0.10.1"
git2 = "0.18.1"
log = "0.4.20"
rusoto_core = "0.48.0"
rusoto_sqs = "0.48.0"
shiplift = "0.7.0"
tokio = "1.35.1"
